-- AlterTable
ALTER TABLE "CoachTemplate" ADD COLUMN     "coachMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "tierMultipliers" JSONB NOT NULL DEFAULT '{"0": 1.0}';

-- AlterTable
ALTER TABLE "Route" ADD COLUMN     "basePricePerKm" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN     "stationFee" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Seat" ADD COLUMN     "tier" INTEGER NOT NULL DEFAULT 0;
